// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLzX6Y_HZp394BSah75ejf6IjxmoQ-7s',
    appId: '1:429596339370:web:65ef3fd12b75728bec34d3',
    messagingSenderId: '429596339370',
    projectId: 'hr-bagong',
    authDomain: 'hr-bagong.firebaseapp.com',
    storageBucket: 'hr-bagong.firebasestorage.app',
    measurementId: 'G-7YGZV9VLBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdn_kuTiOm4U_fpTCyDJWBMokMeatjGVo',
    appId: '1:429596339370:android:74cfc48ae66a0b4aec34d3',
    messagingSenderId: '429596339370',
    projectId: 'hr-bagong',
    storageBucket: 'hr-bagong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa5z3tgTO6a68HOVe7Xk7sxiJgRhPr4EU',
    appId: '1:429596339370:ios:e461e39edd1bd464ec34d3',
    messagingSenderId: '429596339370',
    projectId: 'hr-bagong',
    storageBucket: 'hr-bagong.firebasestorage.app',
    iosBundleId: 'com.example.hrDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa5z3tgTO6a68HOVe7Xk7sxiJgRhPr4EU',
    appId: '1:429596339370:ios:e461e39edd1bd464ec34d3',
    messagingSenderId: '429596339370',
    projectId: 'hr-bagong',
    storageBucket: 'hr-bagong.firebasestorage.app',
    iosBundleId: 'com.example.hrDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHLzX6Y_HZp394BSah75ejf6IjxmoQ-7s',
    appId: '1:429596339370:web:44577761910f6df7ec34d3',
    messagingSenderId: '429596339370',
    projectId: 'hr-bagong',
    authDomain: 'hr-bagong.firebaseapp.com',
    storageBucket: 'hr-bagong.firebasestorage.app',
    measurementId: 'G-LK0QWR4NW8',
  );
}
